### ISSUE TITLE
README ?

### ISSUE THREAD

**Issue by odannyc** [moderntv/recombee#1]
Is this project complete and production ready? If so, it'll be useful to add a readme so we know how to use it.

Thanks!

**Comment by Matovidlo** [comment]
First, sorry that I am responding to you that late.
Yes we have it in production, we'll provide Readme.md file for sure. This project was not maintained for longer time and we will resume to work on it.
I cannot say when it will be done but I am sure that we can push it till the next month

**Comment by Matovidlo** [comment]
@odannyc We have merged the documentation. It should be updated also on https://pkg.go.dev/github.com/moderntv/recombee
